#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Protect master from accidental commits.
echo -e "===\n>> Pre-commit Hook:: Checking branch name ..."
branchName=$(git rev-parse --abbrev-ref HEAD)

if [ $branchName == 'master' ]; then
  echo -e "\n🚫 Commit directly to master branch is not allowed! \n" && exit 1
fi

if [ $branchName == 'main' ]; then
  echo -e "\n🚫 Commit directly to main branch is not allowed! \n" && exit 1
fi

if [ $branchName == 'develop' ]; then
  echo -e "\n🚫 Cannot push to remote develop branch, please create your own branch and use PR.\n" && exit 1
fi

if [[ $branchName = *[![:ascii:]]* ]]; then
  echo -e "\n🚫 Branch name should not have any non-ascii letters, please rename your branch name.\n" && exit 1
fi

if [[ $branchName == *[[:upper:]]* ]]; then
  echo -e "\n🚫 Branch name should not have any UPPER case letters, please rename your branch name.\n" && exit 1
fi

echo -e ">> Finish checking branch name.\n==="

echo -e ">> Run lint-staged.\n==="
npm run lint-staged

# echo -e ">> Run tests.\n==="
# npm test

echo -e ">> Everything looks good. Commiting changes.\n==="
exit 0
